// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uidhqchwbrbybfapaytp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZGhxY2h3YnJieWJmYXBheXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzg1NDMsImV4cCI6MjA2MTg1NDU0M30.RNdWMfkPQXYBf6VceNtCaOPRQT8t-nbr4QgsN0JXSXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);